/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module biestabled_sincrono(D, clk, reset, Q);
  wire _0_;
  wire _1_;
  reg _2_;
  input D;
  wire D;
  output Q;
  wire Q;
  input clk;
  wire clk;
  input reset;
  wire reset;
  assign _0_ = ~ reset;
  assign _1_ = _0_ ? 1'h0 : D;
  always @(negedge clk)
    _2_ <= _1_;
  assign Q = _2_;
endmodule
