/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module biestabled_asincrono(d, clk, q);
  reg _0_;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  always @(posedge clk)
    _0_ <= d;
  assign q = _0_;
endmodule

module boton_a_switch(clk, btn_set, btn_clr, salida);
  wire _0_;
  wire _1_;
  reg _2_ = 1'h0;
  input btn_clr;
  wire btn_clr;
  input btn_set;
  wire btn_set;
  input clk;
  wire clk;
  wire estado;
  output salida;
  wire salida;
  assign _0_ = btn_clr ? 1'h0 : estado;
  assign _1_ = btn_set ? 1'h1 : _0_;
  always @(posedge clk)
    _2_ <= _1_;
  assign estado = _2_;
  assign salida = estado;
endmodule

module main(clk, btn_set, btn_clr, Q);
  wire _0_;
  wire _1_;
  output Q;
  wire Q;
  input btn_clr;
  wire btn_clr;
  input btn_set;
  wire btn_set;
  input clk;
  wire clk;
  wire d_virtual;
  wire \inst_biestable:4 ;
  wire \inst_virtual_switch:1 ;
  biestabled_asincrono inst_biestable (
    .clk(clk),
    .d(d_virtual),
    .q(_1_)
  );
  boton_a_switch inst_virtual_switch (
    .btn_clr(btn_clr),
    .btn_set(btn_set),
    .clk(clk),
    .salida(_0_)
  );
  assign d_virtual = \inst_virtual_switch:1 ;
  assign \inst_virtual_switch:1  = _0_;
  assign \inst_biestable:4  = _1_;
  assign Q = \inst_biestable:4 ;
endmodule
