/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module biestablejk_sincrono(J, K, clk, reset, Q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  reg _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input J;
  wire J;
  input K;
  wire K;
  output Q;
  wire Q;
  input clk;
  wire clk;
  wire dato;
  input reset;
  wire reset;
  assign _11_ = ~ K;
  assign _12_ = _11_ & J;
  assign _13_ = ~ dato;
  assign _01_ = _12_ ? 1'h1 : _13_;
  assign _02_ = _10_ ? 1'h0 : _01_;
  assign _03_ = _08_ ? dato : _02_;
  assign _04_ = _00_ ? 1'h0 : _03_;
  always @(negedge clk)
    _05_ <= _04_;
  assign _00_ = ~ reset;
  assign _06_ = ~ J;
  assign _07_ = ~ K;
  assign _08_ = _07_ & _06_;
  assign _09_ = ~ J;
  assign _10_ = K & _09_;
  assign dato = _05_;
  assign Q = dato;
endmodule
