/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module mux_n(datos, control, salida);
  wire [3:0] _0_;
  wire [3:0] _1_;
  wire [3:0] _2_;
  input [1:0] control;
  wire [1:0] control;
  input [15:0] datos;
  wire [15:0] datos;
  output [3:0] salida;
  wire [3:0] salida;
  wire [31:0] sel;
  assign _0_ = sel[0] ? datos[7:4] : datos[3:0];
  assign _1_ = sel[0] ? datos[15:12] : datos[11:8];
  assign _2_ = sel[1] ? _1_ : _0_;
  assign sel = { 30'h00000000, control };
  assign salida = _2_;
endmodule
