/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module biestablet_asincrono(T, clk, reset, Q);
  wire _0_;
  wire _1_;
  wire _2_;
  reg _3_;
  output Q;
  wire Q;
  input T;
  wire T;
  input clk;
  wire clk;
  wire dato;
  input reset;
  wire reset;
  always @(posedge clk, posedge reset)
    if (reset) _3_ <= 1'h0;
    else _3_ <= _2_;
  assign _0_ = ~ T;
  assign _1_ = ~ dato;
  assign _2_ = _0_ ? dato : _1_;
  assign dato = _3_;
  assign Q = dato;
endmodule
