/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module registro_rot_izqda(clk, reset, Q);
  reg [3:0] _0_;
  output [3:0] Q;
  wire [3:0] Q;
  input clk;
  wire clk;
  wire [3:0] datos;
  input reset;
  wire reset;
  always @(posedge clk, posedge reset)
    if (reset) _0_ <= 4'h3;
    else _0_ <= { datos[2:0], datos[3] };
  assign datos = _0_;
  assign Q = datos;
endmodule
