/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module demux(entrada, control, salida);
  wire _0_;
  wire [1:0] _1_;
  wire _2_;
  wire [1:0] _3_;
  wire _4_;
  wire [1:0] _5_;
  wire _6_;
  wire [1:0] _7_;
  input [1:0] control;
  wire [1:0] control;
  input [1:0] entrada;
  wire [1:0] entrada;
  output [7:0] salida;
  wire [7:0] salida;
  wire [31:0] sel;
  assign _2_ = sel == 32'd1;
  assign _3_ = _2_ ? entrada : 2'h0;
  assign _4_ = sel == 32'd2;
  assign _5_ = _4_ ? entrada : 2'h0;
  assign _6_ = sel == 32'd3;
  assign _7_ = _6_ ? entrada : 2'h0;
  assign _0_ = sel == 32'd0;
  assign _1_ = _0_ ? entrada : 2'h0;
  assign sel = { 30'h00000000, control };
  assign salida = { _7_, _5_, _3_, _1_ };
endmodule
