/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module comparador(A, B, AmayorB, AigualB, AmenorB);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  input [1:0] A;
  wire [1:0] A;
  output AigualB;
  wire AigualB;
  output AmayorB;
  wire AmayorB;
  output AmenorB;
  wire AmenorB;
  input [1:0] B;
  wire [1:0] B;
  assign _4_ = A < B;
  assign _5_ = _4_ ? 1'h1 : 1'h0;
  assign _0_ = A > B;
  assign _1_ = _0_ ? 1'h1 : 1'h0;
  assign _2_ = A == B;
  assign _3_ = _2_ ? 1'h1 : 1'h0;
  assign AmayorB = _1_;
  assign AigualB = _3_;
  assign AmenorB = _5_;
endmodule
