/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module biestablejk_asincrono(J, K, clk, reset, Q);
  wire _00_;
  wire _01_;
  wire _02_;
  reg _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  input J;
  wire J;
  input K;
  wire K;
  output Q;
  wire Q;
  input clk;
  wire clk;
  wire dato;
  input reset;
  wire reset;
  assign _09_ = _08_ & J;
  assign _10_ = ~ dato;
  assign _11_ = _09_ ? 1'h1 : _10_;
  assign _01_ = _07_ ? 1'h0 : _11_;
  assign _02_ = _05_ ? dato : _01_;
  always @(posedge clk, posedge reset)
    if (reset) _03_ <= 1'h0;
    else _03_ <= _02_;
  assign _00_ = ~ J;
  assign _04_ = ~ K;
  assign _05_ = _04_ & _00_;
  assign _06_ = ~ J;
  assign _07_ = K & _06_;
  assign _08_ = ~ K;
  assign dato = _03_;
  assign Q = dato;
endmodule
