/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module contador(en, direccion, reset, clk, cuenta);
  wire _0_;
  wire [2:0] _1_;
  wire [2:0] _2_;
  wire [2:0] _3_;
  wire [2:0] _4_;
  reg [2:0] _5_;
  input clk;
  wire clk;
  wire [2:0] cont;
  output [2:0] cuenta;
  wire [2:0] cuenta;
  input direccion;
  wire direccion;
  input en;
  wire en;
  input reset;
  wire reset;
  assign _2_ = cont - 3'h1;
  assign _3_ = _0_ ? _1_ : _2_;
  assign _4_ = en ? _3_ : cont;
  always @(posedge clk, posedge reset)
    if (reset) _5_ <= 3'h0;
    else _5_ <= _4_;
  assign _0_ = ~ direccion;
  assign _1_ = cont + 3'h1;
  assign cont = _5_;
  assign cuenta = cont;
endmodule
