/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module biestabled_asincrono(D, clk, reset, Q);
  reg _0_;
  input D;
  wire D;
  output Q;
  wire Q;
  input clk;
  wire clk;
  input reset;
  wire reset;
  always @(posedge clk, posedge reset)
    if (reset) _0_ <= 1'h0;
    else _0_ <= D;
  assign Q = _0_;
endmodule
