/* Generated by Yosys 0.51+101 (git sha1 314842d2a, g++ 14.2.1 -fPIC -O3) */

module biestablet_sincrono(T, clk, reset, Q);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  reg _5_;
  output Q;
  wire Q;
  input T;
  wire T;
  input clk;
  wire clk;
  wire dato;
  input reset;
  wire reset;
  always @(negedge clk)
    _5_ <= _4_;
  assign _0_ = ~ reset;
  assign _1_ = ~ T;
  assign _2_ = ~ dato;
  assign _3_ = _1_ ? dato : _2_;
  assign _4_ = _0_ ? 1'h0 : _3_;
  assign dato = _5_;
  assign Q = dato;
endmodule
